function Info = moveandsavenewfilepaths(Info, ses, prevFiles, originalSavePath, processName)
% Save the new file paths
%   Based on the previous files we can decide which files were created by a
%   process and save them automatically
%
%   Inputs:
%       - paths: The usual paths structure that contans all phats and that
%                we aim to expand
%       - prevFiles: Previous files
%                    Note: To get this just use:
%                          prevFiles = dir(paths.functional.nii.path);
%                          or
%                          prevFiles = dir(paths.save.fullPath);
%                          depending where SPM puts the output file
%       - originalSavePath: The path where SPM saves the output for this
%                           job
%       - processName: The name of the process eg:
%                   - preprocessing
%                   - firstla
%                   - secondla
%
%   Outputs:
%       - paths: The expanded path structure
    
    if ses >= Info.Settings.startSession
        % Clean up the prevFiles
        prevFiles = cleanupfiles(prevFiles);

        % Get the current files and clean it up
        currFiles = cleanupfiles(dir(originalSavePath));

        % Delete the files from the current list that were also in the previous
        % file list
        newFiles = currFiles(~ismember(currFiles, prevFiles));

        % Keep only the files that are for the current subject (this is
        % important for cluster computing) (this is only important if we are in
        % the original data directory) and keep only the part of the file name
        % that was added by SPM (except the '_' character)
        [~, newFilesPrefix, exts] = fileparts(newFiles);
        if strcmp(originalSavePath, Info.paths.functionalNii(ses).path)
            newFilesPrefix(~contains(newFilesPrefix, Info.paths.functionalNii(ses).name)) = [];
        end
        newFilesPrefix = replace(newFilesPrefix, {Info.paths.functionalNii(ses).name, '_'}, '');

        if ~iscell(newFilesPrefix)
            % This probably only happens when there was only 1 output file to
            % make my life easier I put this one output into a 1x1 cell
            newFilesPrefix = {newFilesPrefix};
        end

        % If SPM did not add any prefix then try to save in the paths as its
        % extension
        for i = 1:numel(newFilesPrefix)
            if isempty(newFilesPrefix{i})
                newFilesPrefix{i} = replace(exts{i}, '.', '');
            end
        end

        % If there are still empty cells then throw an error (but this is
        % unlikely to happen)
        if any(isempty(newFilesPrefix))
            error('Could not save an output file generated by SPM.');
        end

        % Save these into the path struct
        for i = 1:numel(newFilesPrefix)
            Info.paths.([processName, 'File_', newFilesPrefix{i}])(ses) = getpaths(fullfile(originalSavePath, newFiles{i}));
            %Info.paths.([processName, 'File_', newFilesPrefix{i}])(ses) = move_file_custom(Info.paths.([processName, 'File_', newFilesPrefix{i}])(ses), Info, processName);
        end
    end
end

function files = cleanupfiles(files)
    % Get the file names and delete the '.' and '..' (the first two entry)
    files = {files.name}';
    files = files(~ismember(files, {'.', '..'}));
end


function Info = move_file_custom(filePath, Info, processName)
    % Move a file if needed
    %   Note: In some cases SPM puts its output directly to the save
    %         path and so in these cases the movefile will not be succesful
    %         and so we just return the original path
    if ~strcmp(filePath.path, Info.paths.([processName, 'Save']).fullPath)
        % Move the file
        isMoveSuccessful = movefile(filePath.fullPath, Info.paths.([processName, 'Save']).fullPath);
        
        % Raise an error if the move was not succesful
        if ~isMoveSuccessful
            error(['There was an error moving the file: ', filePath.fullPath]);
        end
        
        % Update the paths
        Info = getpaths(fullfile(Info.paths.([processName, 'Save']).fullPath, [filePath.name, filePath.ext]));
    else
        % If we don't need to move then return the original
        Info = filePath;
    end
end

